### ISSUE TITLE
Shields are at an angle instead of a more vertical stance when blocking or held

### ISSUE THREAD

**Issue by OliverDK75** [SolipIngen/minecraft.progressivearchery#75] opened 2024-07-26 12:51 UTC
I'm gonna provide Mod version and screenshots with and without the mod so the difference can be seen. I don't think this was an intentional change and might've just been a "side effect", hope this can get fixed.

![2024-07-26_14 34 05](https://github.com/user-attachments/assets/965531bd-a4df-48c7-968a-1c23d21a4e4e)
![2024-07-26_14 44 07](https://github.com/user-attachments/assets/ac9c3296-e49a-4232-9b56-f21117ea434d)

Mod Version: progressivearchery-1.1.4-1.20.2+trinkets

**Comment by SolipIngen** [comment] 2024-08-01 07:03
Hello, thank you for reporting this Issue.

Was Progressive Archery the mod you had turned off? Progressive Archery doesn't directly touch anything shield related, but SASSOT (one of my other mods) does. If it was SASSOT that seemed to be causing the issue, I recommend moving this thread to SASSOT's Issues page instead.

Otherwise, let me check if this Issue is present in the latest version of the mod. Back-updating for older versions is not supported, but I can fix this issue in the next mod version.

(Like the skin btw, unfortunate that we cannot see more of the original owner and his rabbit origin anymore.)

**Comment by OliverDK75** [comment] 2024-08-01 10:34
Would SASSOT come within the Progressive Archery mod or is it seperate? I've checked my modpack and it doesnt have SASSOT in it, no trace of the name. I've also just tested in a modpack with the only mod being loaded/active is Progressive Archery.

**Comment by SolipIngen** [comment] 2024-08-02 02:33
Thank you for confirming. I'll check if this is present in the latest version as well.

**Comment by SolipIngen** [comment] 2024-08-06 06:13
Hello. 

This issue has been addressed and fixed in the latest version of Progressive Archery (v1.2.1-1.21). As usual, you can find it on Modrinth and CurseForge.

Please feel free to install the mod and confirm that the issue is fixed. I will close this thread now. If the issue persists, please feel free to re-open this issue, or to open another issue.

**Closed by SolipIngen** 2024-08-06 06:13 UTC
