### ISSUE TITLE
Crafting several items does not work

### ISSUE THREAD

**Issue by Appel-flappen** [SolipIngen/minecraft.progressivearchery#34] opened 2023-05-11 19:33 UTC
I've been trying to craft a few different things from the mod, I have the experimental features enabled. These are things I cannot craft:

- netherite bows (tried using template, bow and netherite ingot, also netherite scrap, no luck.)
- diamond arrows (placed items into table, no result. shows a bucket icon where the string should go?)

Will there also be a list of recipes so we know if things are actually wrong?

**Comment by SolipIngen** [comment] 2023-05-14 00:58
Hello, thank you for writing in.
Netherite bows are upgraded with the vanilla Netherite Upgrade templates from their diamond counterparts, and not with the Bow Fusion template. This should be functioning correctly.
The bucket is also as intended, as it hints towards a lava bucket. The remaining recipes have been intentionally not fully described, such that players can try figuring them out for themselves.
That being said, the mod has integration with the Roughly Enough Items mod, with a recent bug having been fixed in v0.1.9. If you would prefer to know what the recipes are, consider installing Roughly Enough Items, and all recipes should be accessible.

**Closed by SolipIngen** 2023-05-14 00:58 UTC

**Comment by Appel-flappen** [comment] 2023-05-14 18:13
I see, thank you for the response. I did find that the netherite upgrade did work, the lava bucket is rather counter-intuitive however. 
I am using EMI, however not a version for the 1.20 experimental features, so perhaps that's why it does not show any recipes.

thanks
